service: hexaclock
frameworkVersion: '3'

custom:
  tableName: 'employees-table-${sls:stage}'
  accountId: '905418037797'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role: arn:aws:iam::${self:custom.accountId}:role/LabRole
      # statements:
      #   - Effect: Allow
      #     Action:
      #       - dynamodb:Query
      #       - dynamodb:Scan
      #       - dynamodb:GetItem
      #       - dynamodb:PutItem
      #       - dynamodb:UpdateItem
      #       - dynamodb:DeleteItem
      #     Resource:
      #       - Fn::GetAtt: [ EmployeesTable, Arn ]
  environment:
    EMPLOYEES_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: employeeId
            AttributeType: S
        KeySchema:
          - AttributeName: employeeId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
