service: hexaclock
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

custom:
  employeesTableName: 'employees-table-${sls:stage}'
  timeClockTableName: 'timeClock-table-${sls:stage}'
  accountId: '590184086377'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role: arn:aws:iam::${self:custom.accountId}:role/LabRole
      # statements:
      #   - Effect: Allow
      #     Action:
      #       - dynamodb:Query
      #       - dynamodb:Scan
      #       - dynamodb:GetItem
      #       - dynamodb:PutItem
      #       - dynamodb:UpdateItem
      #       - dynamodb:DeleteItem
      #     Resource:
      #       - Fn::GetAtt: [ EmployeesTable, Arn ]
  environment:
    EMPLOYEES_TABLE: ${self:custom.employeesTableName}
    TIMECLOCK_TABLE: ${self:custom.timeClockTableName}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: employeeId
            AttributeType: S
        KeySchema:
          - AttributeName: employeeId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.employeesTableName}
    TimeClockTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: employeeId
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: employeeId
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.timeClockTableName}
        
